### ISSUE TITLE
The new class index page breaches the layout container 

### ISSUE THREAD

**Issue by weitjong** [urho3d/urho3d.github.io#10]

**Comment by friesencr** [comment]
What is a url of the page?

**Comment by weitjong** [comment]
I am not in front of my workstation. The new link is at the second "button" in the HEAD version of the documentation.

**Comment by friesencr** [comment]
Yeah that table is goofed.  The table causes it to overflow its box.  I tried hacking the box model to have the cells display block but the order of the columns are also gnarly.  I don't think there is saving that markup.  I don't know if there is any alternative html generators for the class index.

**Comment by weitjong** [comment]
Thanks for looking into it. I actually may have an idea on how to fix it but just not able to do it immediately. This issue serves the purpose as a reminder.

**Comment by friesencr** [comment]
While it technically is in the container the usability of it is still bad.  I don't think it is worth the effort to fix unless cmake has a different generator.

**Comment by friesencr** [comment]
Setting COLS_IN_ALPHA_INDEX to 3 might make it generally more usable.

**Comment by weitjong** [comment]
That's a good idea. We can change the config setting to 3 just for our main website and leave the default to 5 for doc generation in user own environment.

**Comment by friesencr** [comment]
Looks good :+1:
