### ISSUE TITLE
All "blog" entries are generated with invalid links to stylesheet and javascripts.

### ISSUE THREAD

**Issue by weitjong** [urho3d/urho3d.github.io#11]
Not sure yet if this was a one-off site generation issue or there is something being changed on the GitHub pages which causes this issue. To be investigated later.

**Comment by friesencr** [comment]
Jekyll 3 just rolled out.  Bundle update is a good start.

**Comment by weitjong** [comment]
Confirmed the issue was caused by Jekyll 3.0 released.
