### ISSUE TITLE
Broken samples page

### ISSUE THREAD

**Issue by Modanung** [urho3d/urho3d.github.io#20]
This is what the samples page looks like on my computer:

![image](https://cloud.githubusercontent.com/assets/7316241/24527093/0c528b08-15a1-11e7-835a-493ba7e00362.png)

Just languages, no samples.

**Comment by weitjong** [comment]
Thanks for reporting it. I thought I have fixed that. Apparently not when last commit triggered a packaging CI build. Will fix later tonight.

**Comment by weitjong** [comment]
Managed to do that while commuting.
