### ISSUE TITLE
Discourse forum is down - can't find another way to contact anyone about it

### ISSUE THREAD

**Issue by radishdalek** [urho3d/urho3d.github.io#24]
The discourse forum is down and has been for at least several days. 

There doesn't seem to any way to contact anyone about the problem other than github issues or the forum (which is down). 

I would suggest the possible addition of a social media account (such as twitter) for another point of contact.  With a visible twitter account a tweet could state when there was a problem known to the team 
E.G. "Forum currently down, working on it, eta 1 week to fix"
At a glance, people would know whether a site problem was already known, otherwise they could then contact the website team through twitter to notify them of the unknown problem.

If sections of a website go dead without some form of notification somewhere about fixing the problem, people may get the wrong impression about the state of the project.

**Comment by weitjong** [comment]
The forum is OK on my side now and the last few times I checked it. Although occasionally the forum went down on me as well, but usually it would get back online again after awhile. The forum is a free service from Discourse, so can't complain much. Are you sure it is not just down on your side?

**Comment by radishdalek** [comment]
I try the forum and I get "This site can’t be reached"
Testing on site down testers:
https://down.com/ - states its down for everyone
https://downforeveryoneorjustme.com/discourse.urho3d.io - states its just down for me

It is a bit strange

**Comment by weitjong** [comment]
I am afraid you will have to check with your ISP for this issue. Closing this as there is nothing we can do on our side.
